### ISSUE TITLE
Visualization problems on IOS phone

### ISSUE THREAD

**Issue by FoFFolo** [EkType/Honk#15]
this font is not properly well visualized on Iphone(I don't know if on Android too). The problem is that the linear gradient colors inside the Honk font don't show up at all, but only the black corners.
![Serratore Federico Portfolio jpeg](https://github.com/EkType/Honk/assets/74419371/7372fc1f-5416-4512-a34c-24e9641186ba)

**Comment by girish-dalvi** [comment]
COLR/CPAL(v1) Font Formats are as of today, not supported on the Safari browser, and hence the gradients do not show up. This is a browser compatibility issue and not a font issue.
